(() => {
  'use strict';

  const BUTTON_ID='universalLineageBtn',PANEL_ID='universalLineagePanel',MODAL_ID='lineageHandoffModal',STYLE_ID='soutu-provenance-lineage-style',HANDOFF_SESSION='soutu-pro-lineage-handoff-v1';
  const KEYS={results:'soutu-pro-v9-results',cases:'soutu-pro-v9-cases',evidence:'soutu-pro-v9-evidence',weights:'soutu-pro-v9-weights',view:'soutu-pro-v9-view'};
  let lastFamilies=[],reportObserver=null,enhancingReport=false;
  const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':c.charCodeAt(0)===34?'&quot;':'&#39;');
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
  const parseDate=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?t:0};
  const toast=(a,b='',tone='ok')=>window.SOUTU_BRIDGE?.toast?.(a,b,tone);
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const read=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};

  function injectStyle(){
    if(document.getElementById(STYLE_ID))return;
    const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
      .universal-lineage-panel{margin-top:12px;padding:14px;border:1px solid var(--line);border-radius:16px;background:var(--panel)}
      .lineage-head,.lineage-family-title{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.lineage-head{margin-bottom:12px}.lineage-head span,.lineage-node small,.lineage-root small{display:block;margin-top:3px;color:var(--muted);font-size:9px}.lineage-head-actions,.lineage-summary,.lineage-edge-meta{display:flex;gap:6px;flex-wrap:wrap}.lineage-head-actions button{height:30px;padding:0 9px;border:1px solid var(--line);border-radius:8px;background:var(--panel);font-size:9px;font-weight:750}.lineage-head-actions [data-lineage-handoff]{background:var(--primary-soft);color:var(--primary)}
      .lineage-summary{margin-bottom:12px}.lineage-summary span,.lineage-edge-meta span{padding:4px 7px;border:1px solid var(--line);border-radius:999px;background:var(--panel-subtle);font-size:9px;color:var(--muted)}.lineage-summary b{color:var(--text)}.lineage-families{display:grid;gap:12px}.lineage-family{padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--panel-subtle)}.lineage-family-title{margin-bottom:9px}.lineage-root,.lineage-node{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;padding:9px 10px;border:1px solid var(--line);border-radius:11px;background:var(--panel)}.lineage-root{border-color:color-mix(in srgb,var(--primary) 32%,var(--line))}.lineage-root a,.lineage-node a{font-size:9px;color:var(--primary);text-decoration:none}.lineage-badge{display:inline-flex;margin-bottom:4px;padding:3px 6px;border-radius:999px;background:var(--primary-soft);color:var(--primary);font-size:8px;font-weight:800}.lineage-branches{display:grid;gap:8px;margin-top:8px;padding-left:16px;border-left:1px solid var(--line-strong)}.lineage-edge-meta{margin-bottom:5px}.lineage-edge-meta .supported{color:var(--success)}.lineage-edge-meta .uncertain{color:var(--warning)}.lineage-edge-meta .conflict{color:var(--danger)}.lineage-node em{display:block;margin-top:4px;font-size:8px;font-style:normal;color:var(--muted)}.lineage-empty{padding:12px;text-align:center;color:var(--muted);font-size:10px}
      .lineage-handoff-modal{max-width:560px}.lineage-handoff-grid{display:grid;gap:12px}.lineage-handoff-grid label{display:grid;gap:6px;font-size:10px;font-weight:750}.lineage-handoff-grid select,.lineage-handoff-grid input{min-height:40px;width:100%;padding:0 10px;border:1px solid var(--line);border-radius:10px;background:var(--panel);color:var(--text)}.lineage-handoff-summary{padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--panel-subtle);font-size:10px;color:var(--muted)}
      .lineage-report-section{margin-top:24px}.lineage-report-section table{width:100%;border-collapse:collapse}.lineage-report-section th,.lineage-report-section td{padding:6px;border:1px solid #cfd6df;vertical-align:top;font-size:9px;text-align:left}.lineage-report-section small{display:block;margin-top:3px}
      @media(max-width:620px){.lineage-head{display:grid}.lineage-root,.lineage-node{grid-template-columns:1fr}}@media print{.lineage-report-section{break-before:page}}
    `;document.head.appendChild(s)
  }

  function ensureModal(){
    if(document.getElementById(MODAL_ID))return;
    const m=document.createElement('div');m.id=MODAL_ID;m.className='modal-backdrop hidden';m.innerHTML=`<div class="modal lineage-handoff-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>送入 Investigation Hub</h2><p>保存为 V9 Evidence，并可关联 Case。</p></div><button class="icon-btn" data-lineage-handoff-close aria-label="关闭"><svg><use href="#i-x"></use></svg></button></div><div class="lineage-handoff-grid"><div class="lineage-handoff-summary" id="lineageHandoffSummary"></div><label>交接方式<select id="lineageHandoffMode"><option value="evidence">仅保存到 Evidence</option><option value="new">新建 Case 并关联</option><option value="existing">关联已有 Case</option></select></label><label id="lineageNewCaseRow" class="hidden">Case 名称<input id="lineageNewCaseName" maxlength="120"></label><label id="lineageExistingCaseRow" class="hidden">选择 Case<select id="lineageExistingCase"></select></label><div class="v9-action-row"><button class="secondary-btn" data-lineage-handoff-close>取消</button><button class="primary-btn" data-lineage-handoff-confirm>保存并进入 Hub</button></div></div></div>`;document.body.appendChild(m)
  }

  function ensureUi(){
    injectStyle();ensureModal();
    const p=document.getElementById('universalProvenanceBtn');if(p&&!document.getElementById(BUTTON_ID)){const b=document.createElement('button');b.id=BUTTON_ID;b.className='secondary-btn compact';b.innerHTML='<svg><use href="#i-history"></use></svg>版本链';p.insertAdjacentElement('afterend',b)}
    const insights=document.getElementById('universalInsights');if(insights&&!document.getElementById(PANEL_ID)){const el=document.createElement('div');el.id=PANEL_ID;el.className='universal-lineage-panel hidden';insights.insertAdjacentElement('afterend',el)}
  }

  function resultMap(){const m=new Map();document.querySelectorAll('.universal-result-card').forEach(card=>{const title=clean(card.querySelector('.universal-result-body>b')?.textContent),a=card.querySelector('.universal-media[href]');if(title)m.set(title,{title,url:a?.href||'',domain:(()=>{try{return new URL(a?.href||'').hostname.replace(/^www\./,'')}catch{return''}})()})});return m}
  function timelineMap(){const m=new Map();document.querySelectorAll('#universalInsights .provenance-timeline a').forEach(a=>{const title=clean(a.querySelector('b')?.textContent);if(title){const date=clean(a.querySelector('time')?.textContent);m.set(title,{date,time:parseDate(date),source:clean(a.querySelector('span')?.textContent),url:a.href||''})}});return m}
  function directionEvidence(root,child){if(root?.time&&child?.time){if(root.time<=child.time)return{label:'时间支持',tone:'supported',reason:`${root.date} → ${child.date}`};return{label:'时间冲突',tone:'conflict',reason:`子项日期 ${child.date} 早于候选根节点 ${root.date}`}}return{label:'方向待验证',tone:'uncertain',reason:'至少一端缺少可验证日期'}}

  function collect(){
    const links=resultMap(),times=timelineMap(),families=[];
    document.querySelectorAll('#universalInsights .provenance-family-card').forEach((card,i)=>{const id=card.dataset.provenanceFamily||`family-${i}`,candidateTitle=clean(card.querySelector(':scope>strong')?.textContent),relations=[...card.querySelectorAll('.provenance-relation')].map(row=>({type:clean(row.querySelector('span')?.textContent),confidence:clean(row.querySelector('b')?.textContent),title:clean(row.querySelector('small')?.textContent),reasons:clean(row.querySelector('em')?.textContent)})).filter(x=>x.title),root=relations.find(x=>/original candidate/i.test(x.type))||relations.find(x=>x.title===candidateTitle)||{type:'Original candidate',title:candidateTitle,reasons:'来源证据最高候选'},rootMeta=times.get(root.title)||{},variants=relations.filter(x=>x!==root&&x.title!==root.title).map(x=>({...x,...(times.get(x.title)||{}),...(links.get(x.title)||{}),direction:directionEvidence(rootMeta,times.get(x.title)||{})}));families.push({id,label:clean(card.querySelector('.provenance-family-head span')?.textContent)||`图片家族 ${i+1}`,root:{...root,...(links.get(root.title)||{}),...rootMeta},variants})});return families
  }

  function evidencePayload(families=lastFamilies){
    const rows=families.flatMap(f=>[{familyId:f.id,familyLabel:f.label,role:'candidate-root',title:f.root.title||'',relationType:f.root.type||'Original candidate',relationConfidence:f.root.confidence||'',directionState:'candidate-root',directionReason:'来源证据最高候选；不代表已验证原创',date:f.root.date||'',source:f.root.source||'',domain:f.root.domain||'',url:f.root.url||'',reasons:f.root.reasons||''},...f.variants.map(v=>({familyId:f.id,familyLabel:f.label,role:'variant',title:v.title||'',relationType:v.type||'Variant',relationConfidence:v.confidence||'',directionState:v.direction?.label||'方向待验证',directionReason:v.direction?.reason||'',date:v.date||'',source:v.source||'',domain:v.domain||'',url:v.url||'',reasons:v.reasons||''}))]);
    return{schema:'soutu-pro.provenance-lineage.v1',generatedAt:new Date().toISOString(),disclaimer:'所有根节点与传播方向均为证据候选；时间缺失或冲突时不得视为已验证原创或确定传播顺序。',summary:{families:families.length,relations:families.reduce((n,f)=>n+f.variants.length,0),timeSupported:rows.filter(r=>r.directionState==='时间支持').length,pending:rows.filter(r=>r.directionState==='方向待验证').length,timeConflicts:rows.filter(r=>r.directionState==='时间冲突').length},families,rows}
  }

  function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function exportJson(){const p=evidencePayload();if(!p.rows.length)return toast('没有可导出的版本链','请先建立版本链。','error');download(`soutu-lineage-${Date.now()}.json`,JSON.stringify(p,null,2),'application/json');toast('版本链 JSON 已导出',`${p.summary.families} 个家族 · ${p.summary.relations} 条关系`,'ok')}
  function exportCsv(){const p=evidencePayload();if(!p.rows.length)return toast('没有可导出的版本链','请先建立版本链。','error');const h=['family_id','family_label','role','title','relation_type','relation_confidence','direction_state','direction_reason','date','source','domain','url','reasons'],vals=r=>[r.familyId,r.familyLabel,r.role,r.title,r.relationType,r.relationConfidence,r.directionState,r.directionReason,r.date,r.source,r.domain,r.url,r.reasons],q=v=>`"${String(v??'').replace(/"/g,'""')}"`,csv=[h,...p.rows.map(vals)].map(r=>r.map(q).join(',')).join('\n');download(`soutu-lineage-${Date.now()}.csv`,'\uFEFF'+csv,'text/csv;charset=utf-8');toast('版本链 CSV 已导出',`${p.rows.length} 条证据记录`,'ok')}

  const lineageKey=r=>[r.familyId,r.role,r.title,r.url,r.relationType,r.directionState].map(clean).join('|');
  function lineageEvidenceRecords(p=evidencePayload()){const capturedAt=Date.now();return p.rows.map(r=>({id:uid(),capturedAt,title:r.title||r.familyLabel||'版本链证据',url:r.url||'',domain:r.domain||'',price:'',product:{},engine:'provenance-lineage',manualLabel:'',kind:'provenance-lineage',lineageKey:lineageKey(r),note:[r.familyLabel,r.role==='candidate-root'?'候选根节点':r.relationType,r.relationConfidence,r.directionState,r.directionReason,r.date,r.source,r.reasons].filter(Boolean).join(' · '),lineage:{schema:p.schema,disclaimer:p.disclaimer,...r}}))}
  function mergeLineageEvidence(existing,incoming,limit=120){const seen=new Set(),out=[];for(const e of [...incoming,...existing]){const key=e.lineageKey||((e.kind==='provenance-lineage'||e.lineage)?lineageKey(e.lineage||{}):`evidence:${e.id||uid()}`);if(seen.has(key))continue;seen.add(key);out.push(e);if(out.length>=limit)break}return out}
  function sourceSnapshot(){const s=window.SOUTU_BRIDGE?.source?.()||{},u=String(s.activeUrl||'');return{name:s.name||'',thumb:u.startsWith('data:')&&u.length<120000?u:''}}
  function handoffToHub({mode='evidence',caseName='',caseId='',payload=evidencePayload(),reload=true}={}){
    if(!payload.rows.length){toast('没有可保存的版本链','请先建立版本链。','error');return{ok:false,reason:'empty'}}
    const incoming=lineageEvidenceRecords(payload),merged=mergeLineageEvidence(read(KEYS.evidence,[]),incoming,120);if(!write(KEYS.evidence,merged)){toast('Evidence 保存失败','本机存储空间不足。','error');return{ok:false,reason:'storage'}}
    let linkedCaseId='';if(mode==='new'||mode==='existing'){const cases=read(KEYS.cases,[]);if(mode==='new'){const c={id:uid(),name:clean(caseName)||`版本链调查 ${new Date().toLocaleDateString()}`,createdAt:Date.now(),source:sourceSnapshot(),query:window.SOUTU_BRIDGE?.primaryQuery?.()||'',results:read(KEYS.results,[]).slice(0,50),evidence:mergeLineageEvidence([],incoming,40),weights:read(KEYS.weights,{visual:.5,structure:.3,text:.2}),lineageSummary:payload.summary};cases.unshift(c);linkedCaseId=c.id}else{const c=cases.find(x=>x.id===caseId);if(!c){toast('Case 不存在','请重新选择调查项目。','error');return{ok:false,reason:'case-not-found'}}c.evidence=mergeLineageEvidence(c.evidence||[],incoming,40);c.lineageSummary=payload.summary;linkedCaseId=c.id}if(!write(KEYS.cases,cases.slice(0,40))){toast('Case 关联失败','本机存储空间不足。','error');return{ok:false,reason:'case-storage'}}}
    write(KEYS.view,'evidence');const result={ok:true,mode,caseId:linkedCaseId,rows:payload.rows.length,saved:merged.filter(e=>e.kind==='provenance-lineage'||e.lineage).length,summary:payload.summary};if(!reload){toast('版本链已送入 Investigation Hub',`${result.rows} 条 lineage 证据${linkedCaseId?' · 已关联 Case':''}`,'ok');return result}try{sessionStorage.setItem(HANDOFF_SESSION,JSON.stringify(result))}catch{}location.reload();return result
  }

  function renderHandoffMode(){const v=document.getElementById('lineageHandoffMode')?.value;document.getElementById('lineageNewCaseRow')?.classList.toggle('hidden',v!=='new');document.getElementById('lineageExistingCaseRow')?.classList.toggle('hidden',v!=='existing')}
  function openHandoffModal(){const p=evidencePayload();if(!p.rows.length)return toast('没有可保存的版本链','请先建立版本链。','error');ensureModal();const cases=read(KEYS.cases,[]),sel=document.getElementById('lineageExistingCase'),mode=document.getElementById('lineageHandoffMode');document.getElementById('lineageHandoffSummary').innerHTML=`<b>${p.summary.families}</b> 个图片家族 · <b>${p.rows.length}</b> 条 Evidence · ${p.summary.timeSupported} 时间支持 · ${p.summary.pending} 待验证 · ${p.summary.timeConflicts} 冲突`;sel.innerHTML=cases.length?cases.map(c=>`<option value="${esc(c.id)}">${esc(c.name||'未命名 Case')}</option>`).join(''):'<option value="">暂无 Case</option>';mode.querySelector('[value="existing"]').disabled=!cases.length;mode.value='evidence';document.getElementById('lineageNewCaseName').value=window.SOUTU_BRIDGE?.primaryQuery?.()||'';renderHandoffMode();document.getElementById(MODAL_ID).classList.remove('hidden')}
  const closeHandoffModal=()=>document.getElementById(MODAL_ID)?.classList.add('hidden');
  function confirmHandoff(){const result=handoffToHub({mode:document.getElementById('lineageHandoffMode')?.value||'evidence',caseName:document.getElementById('lineageNewCaseName')?.value||'',caseId:document.getElementById('lineageExistingCase')?.value||''});if(result?.ok)closeHandoffModal()}

  function appendReportEvidence(target=document.getElementById('v9PrintReport')){
    if(!target||target.querySelector('.lineage-report-section'))return 0;const all=read(KEYS.evidence,[]),rows=all.filter(e=>e.kind==='provenance-lineage'||e.lineage).map(e=>e.lineage||{}).filter(r=>r.familyId||r.title);if(!rows.length)return 0;const disclaimer=all.find(e=>e.lineage?.disclaimer)?.lineage?.disclaimer||'根节点与传播方向属于证据候选，不代表已验证原创或确定传播顺序。',role=r=>r.role==='candidate-root'?'候选根节点':'衍生版本';target.insertAdjacentHTML('beforeend',`<section class="lineage-report-section"><h2>版本传播链证据</h2><p>${esc(disclaimer)}</p><table><thead><tr><th>图片家族</th><th>角色 / 节点</th><th>关系</th><th>置信度</th><th>方向状态</th><th>时间 / 来源</th><th>依据</th></tr></thead><tbody>${rows.slice(0,120).map(r=>`<tr><td>${esc(r.familyLabel||r.familyId||'')}</td><td><b>${esc(role(r))}</b><small>${esc(r.title||'')}</small></td><td>${esc(r.relationType||'')}</td><td>${esc(r.relationConfidence||'')}</td><td><b>${esc(r.directionState||'')}</b><small>${esc(r.directionReason||'')}</small></td><td>${esc(r.date||'')}<small>${esc(r.source||r.domain||'')}</small><small>${esc(r.url||'')}</small></td><td>${esc(r.reasons||'')}</td></tr>`).join('')}</tbody></table></section>`);return rows.length
  }
  function setupReportObserver(){const t=document.getElementById('v9PrintReport');if(!t||reportObserver)return;reportObserver=new MutationObserver(()=>{if(enhancingReport||!t.innerHTML||t.querySelector('.lineage-report-section'))return;enhancingReport=true;try{appendReportEvidence(t)}finally{enhancingReport=false}});reportObserver.observe(t,{childList:true,subtree:false})}

  function render(families){
    const panel=document.getElementById(PANEL_ID);if(!panel)return;lastFamilies=families;const useful=families.filter(f=>f.root?.title&&(f.variants.length||families.length===1)),edges=useful.reduce((n,f)=>n+f.variants.length,0),supported=useful.reduce((n,f)=>n+f.variants.filter(v=>v.direction.tone==='supported').length,0),uncertain=useful.reduce((n,f)=>n+f.variants.filter(v=>v.direction.tone==='uncertain').length,0),conflicts=useful.reduce((n,f)=>n+f.variants.filter(v=>v.direction.tone==='conflict').length,0);panel.classList.remove('hidden');panel.innerHTML=`<div class="lineage-head"><div><b>版本传播链</b><span>根节点与传播方向属于证据候选；无日期时不强行推定先后。</span></div><div class="lineage-head-actions"><button data-lineage-handoff>送入 Investigation Hub</button><button data-lineage-export="json">导出 JSON</button><button data-lineage-export="csv">导出 CSV</button></div></div><div class="lineage-summary"><span><b>${useful.length}</b> 家族</span><span><b>${edges}</b> 关系</span><span><b>${supported}</b> 时间支持</span>${uncertain?`<span><b>${uncertain}</b> 待验证</span>`:''}${conflicts?`<span><b>${conflicts}</b> 时间冲突</span>`:''}</div><div class="lineage-families">${useful.length?useful.map((f,i)=>`<section class="lineage-family" data-lineage-family="${esc(f.id)}"><div class="lineage-family-title"><b>${esc(f.label||`图片家族 ${i+1}`)}</b><span>${f.variants.length+1} 个版本</span></div><div class="lineage-root"><div><span class="lineage-badge">候选根节点</span><b>${esc(f.root.title)}</b><small>${esc([f.root.date,f.root.source,f.root.domain].filter(Boolean).join(' · ')||'日期 / 来源信息不足')}</small></div>${f.root.url?`<a href="${esc(f.root.url)}" target="_blank" rel="noopener noreferrer">打开来源</a>`:''}</div><div class="lineage-branches">${f.variants.length?f.variants.map(v=>`<div class="lineage-edge"><div class="lineage-edge-meta"><span>${esc(v.type||'Variant')}</span>${v.confidence?`<span>${esc(v.confidence)}</span>`:''}<span class="${esc(v.direction.tone)}" title="${esc(v.direction.reason)}">${esc(v.direction.label)}</span></div><div class="lineage-node"><div><b>${esc(v.title)}</b><small>${esc([v.date,v.source,v.domain].filter(Boolean).join(' · ')||'日期 / 来源信息不足')}</small>${v.reasons?`<em>${esc(v.reasons)}</em>`:''}</div>${v.url?`<a href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">打开来源</a>`:''}</div></div>`).join(''):'<div class="lineage-empty">当前家族没有可展示的衍生版本关系。</div>'}</div></section>`).join(''):'<div class="lineage-empty">请先运行“溯源分析”，并确保至少存在一个可识别的图片家族。</div>'}</div>`
  }

  const waitFor=(sel,timeout=15000)=>new Promise((resolve,reject)=>{const hit=document.querySelector(sel);if(hit)return resolve(hit);const o=new MutationObserver(()=>{const el=document.querySelector(sel);if(el){o.disconnect();clearTimeout(timer);resolve(el)}});o.observe(document.documentElement,{childList:true,subtree:true});const timer=setTimeout(()=>{o.disconnect();reject(new Error('等待溯源结果超时'))},timeout)});
  async function openLineage(){ensureUi();const b=document.getElementById(BUTTON_ID),panel=document.getElementById(PANEL_ID);if(!b||!panel)return;if(b.classList.contains('active')){b.classList.remove('active');panel.classList.add('hidden');return}b.disabled=true;b.textContent='构建中…';try{if(!document.querySelector('#universalInsights .provenance-family-card')){const p=document.getElementById('universalProvenanceBtn');if(!p)throw new Error('溯源分析入口不可用');if(!p.classList.contains('active'))p.click();await waitFor('#universalInsights .provenance-family-card')}const f=collect();render(f);b.classList.add('active');toast('版本链已建立',`${f.length} 个图片家族 · ${f.reduce((n,x)=>n+x.variants.length,0)} 条候选关系`,'ok')}catch(e){panel.classList.add('hidden');toast('版本链建立失败',e?.message||'请先完成溯源分析。','error')}finally{b.disabled=false;b.innerHTML='<svg><use href="#i-history"></use></svg>版本链'}}
  function resumeHandoff(){let p=null;try{p=JSON.parse(sessionStorage.getItem(HANDOFF_SESSION)||'null');sessionStorage.removeItem(HANDOFF_SESSION)}catch{}if(p?.ok)setTimeout(()=>{window.SOUTU_BRIDGE?.setView?.('research');toast('版本链已进入 Investigation Hub',`${p.rows} 条 Evidence${p.caseId?' · 已关联 Case':''}`,'ok')},0)}

  function mount(){ensureUi();setupReportObserver();resumeHandoff();document.getElementById(BUTTON_ID)?.addEventListener('click',openLineage);document.getElementById(PANEL_ID)?.addEventListener('click',e=>{if(e.target.closest('[data-lineage-handoff]'))return openHandoffModal();const b=e.target.closest('[data-lineage-export]');if(b)(b.dataset.lineageExport==='json'?exportJson:exportCsv)()});document.getElementById(MODAL_ID)?.addEventListener('click',e=>{if(e.target===e.currentTarget||e.target.closest('[data-lineage-handoff-close]'))return closeHandoffModal();if(e.target.closest('[data-lineage-handoff-confirm]'))confirmHandoff()});document.getElementById('lineageHandoffMode')?.addEventListener('change',renderHandoffMode);window.addEventListener('soutu:source-changed',()=>{lastFamilies=[];document.getElementById(PANEL_ID)?.classList.add('hidden');document.getElementById(BUTTON_ID)?.classList.remove('active')})}

  window.SOUTU_PROVENANCE_LINEAGE={collect,directionEvidence,evidencePayload,lineageEvidenceRecords,mergeLineageEvidence,handoffToHub,appendReportEvidence,render,open:openLineage,exportJson,exportCsv};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
